package com.example.weatherandroidapplication.models

import WeatherX

data class Data(
    val app_temp2: Double = 0.0,
    val aqi: Int = 0,
    val city_name: String,
    val clouds: Int,
    val country_code: String,
    val datetime: String,
    val dewpt: Double,
    val dhi: Double,
    val dni: Double,
    val elev_angle: Double,
    val ghi: Double,
    val gust: Any,
    val h_angle: Int,
    val lat: Double,
    val lon: Double,
    val ob_time: String,
    val pod: String,
    val precip: Any,
    val pres: Double,
    val rh: Int,
    val slp: Int,
    val snow: Any,
    val solar_rad: Double,
    val sources: List<String>,
    val state_code: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Int,
    val timezone: String,
    val ts: Double,
    val uv: Double,
    val vis: Int,
    val weather: WeatherX,
    val wind_cdir: String,
    val wind_cdir_full: String,
    val wind_dir: Int,
    val wind_spd: Double,
)